### ISSUE TITLE
Error: Error("expected value", line: 1, column: 1)

### ISSUE THREAD

**Issue by konkerama** [udondan/cfn-teleport#167]
Hello,

First of all this tools looks really useful and could solve our hands a lot.
I'm trying to implement a simple POC of this tool but I'm stuck having an ambiguous error.

I have created the 2 following simple CF Stacks 
Stack1:
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an S3 bucket to store logs."

Resources:
  MyBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket-123-logs-1-eu-west-1

  SecondBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket-123-logs-eu-west-1-second-bucket
```
Stack2:
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an S3 bucket to store logs."

Resources:
  MyBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket-456-logs-2-eu-west-1

  SecondBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket-456-logs-eu-west-1-second-bucket
```

I want to to a transfer of `MyBucket1` from `Stack1` to `Stack2`.

But when I run the following command:
`cfn-teleport --source Stack1 --target Stack2 --resource MyBucket1 --yes`

I get the output:
```
The following resources will be moved from stack Stack1 to Stack2:
  AWS::S3::Bucket    MyBucket1    mybucket-123-logs-1-eu-west-1
Error: Error("expected value", line: 1, column: 1)
```

Notes:
I run cfn-teleport version 0.4.0.
cfn-teleport is installed via cargo on ubuntu 20.04 LTS
cfn-teleport can communicate successfully with my AWS Account because when I don't provide the flags for Stacks and Resources I can find them and select them using the CLI wizard.

Am I missing something?
